# Generated by Django 4.1.5 on 2023-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dateEnrg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
